# Generated by Django 6.0.5 on 2026-07-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="商品コード"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("洋画", "洋画"),
                            ("邦画", "邦画"),
                            ("アニメ", "アニメ"),
                            ("ドラマ", "ドラマ"),
                            ("ホラー", "ホラー"),
                            ("SF", "SF"),
                            ("コメディ", "コメディ"),
                            ("ドキュメンタリー", "ドキュメンタリー"),
                            ("その他", "その他"),
                        ],
                        max_length=30,
                        verbose_name="ジャンル",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="作品説明")),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="総在庫数"),
                ),
                (
                    "rented",
                    models.PositiveIntegerField(default=0, verbose_name="貸出中"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="videos/",
                        verbose_name="ジャケット画像",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="発売日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
    ]
